base_url = "https://srayan.in"
title = "Srayan"
theme="DeepThought"
compile_sass = true
build_search_index = true
minify_html = true

# Enable external libraries
[extra]
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/categories", name = "Categories" },
 ]},
]

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon.ico"
favicon_32x32 = "/icons/favicon.ico"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "Srayan"
avatar = "/images/avatar.png"

# Social links
[extra.social]
github = "SrayanBhattacharyya"
linkedin = "srayanbhattacharyya"
codeforces = "UnexpectedValue"
reddit = "SurgeImpedance"
pinterest = "srayanbhattacharyya"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[translations]


[languages]
