base_url = "https://srayan.in"
theme="DeepThought"
compile_sass = true
build_search_index = true
minify_html = true

# Enable external libraries
[extra]
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/categories", name = "Categories" },
 ]},
]

taxonomies = [
    { name = "tags", feed = true},
    { name = "categories", feed = true},
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "Srayan"
avatar = "/images/avatar.png"

# Social links
[extra.social]
github = "SrayanBhattacharyya"
linkedin = "srayanbhattacharyya"
codeforces = "UnexpectedValue"
reddit = "SurgeImpedance"
pinterest = "srayanbhattacharyya"

